
- name: Install/update mongo client
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mongodb-org-shell
    - mongodb-org-tools
  notify:
    - reload systemd


- name: Update mongo client
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - mongodb-org-shell
    - mongodb-org-tools
  when: mongodb_upgrade
  notify:
    - reload systemd
