
- name: Install/update mongo client
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mongodb-org-shell
    - mongodb-org-tools


- name: Update mongo client
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - mongodb-org-shell
    - mongodb-org-tools
  when: mongo_upgrade
