---

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"


- name: Include installation tasks
  include_tasks: "install.{{ ansible_os_family | lower }}.yml"
  tags: [mongodb]


- import_tasks: client.yml
  when: mongodb_client == True
  tags: "mongo:client"


- import_tasks: tools.yml
  when: mongodb_tools == True
  tags: "mongo:tools"


- import_tasks: server.yml
  when: mongodb_server == True
  tags: "mongo:server"